#!/bin/bash

# nominal value
curl -O -J https://www.hepdata.net/download/submission/ins1604271/1/root -O HEPData-ins1604271-v1-root.tar.gz
tar xvzf HEPData-ins1604271-v1-root.tar.gz

# replicas 
curl -O -J "https://www.hepdata.net/record/resource/844743?view=true"
curl -O -J "https://www.hepdata.net/record/resource/844750?view=true"
curl -O -J "https://www.hepdata.net/record/resource/844757?view=true"
curl -O -J "https://www.hepdata.net/record/resource/844764?view=true"
curl -O -J "https://www.hepdata.net/record/resource/844771?view=true"
curl -O -J "https://www.hepdata.net/record/resource/844778?view=true"
tar xvzf hepdata_tables_data_antiktr04_eta1_replicas.tar.gz
tar xvzf hepdata_tables_data_antiktr04_eta2_replicas.tar.gz
tar xvzf hepdata_tables_data_antiktr04_eta3_replicas.tar.gz
tar xvzf hepdata_tables_data_antiktr04_eta4_replicas.tar.gz
tar xvzf hepdata_tables_data_antiktr04_eta5_replicas.tar.gz
tar xvzf hepdata_tables_data_antiktr04_eta6_replicas.tar.gz
# need to avoid an "argument list too long" issue
for name in hep*txt; do
    chmod -x $name
done

rm *gz
